Trabajoempleados/Models/CATEGORIA.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trabajoempleados.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CATEGORIA
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
    }
}

Trabajoempleados/Controllers/BCANDIDATOS1Controller.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Trabajoempleados.Models;

namespace Trabajoempleados.Controllers
{
    public class BCANDIDATOS1Controller : Controller
    {
        private bolsaempleosEntities db = new bolsaempleosEntities();

        // GET: BCANDIDATOS1
        public ActionResult Index()
        {
            return View(db.CANDIDATOS.ToList());
        }

        // GET: BCANDIDATOS1/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CANDIDATOS cANDIDATOS = db.CANDIDATOS.Find(id);
            if (cANDIDATOS == null)
            {
                return HttpNotFound();
            }
            return View(cANDIDATOS);
        }

        // GET: BCANDIDATOS1/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: BCANDIDATOS1/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IdCandidato,Cedula,Nombre,Apellido,Correo,Telefono,Contrasena,fechanacimiento")] CANDIDATOS cANDIDATOS)
        {
            if (ModelState.IsValid)
            {
                db.CANDIDATOS.Add(cANDIDATOS);
                db.SaveChanges();
                return RedirectToAction("Login", "Login");
            }

            return View(cANDIDATOS);
        }

        // GET: BCANDIDATOS1/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CANDIDATOS cANDIDATOS = db.CANDIDATOS.Find(id);
            if (cANDIDATOS == null)
            {
                return HttpNotFound();
            }
            return View(cANDIDATOS);
        }

        // POST: BCANDIDATOS1/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IdCandidato,Cedula,Nombre,Apellido,Correo,Telefono,Contrasena,fechanacimiento")] CANDIDATOS cANDIDATOS)
        {
            if (ModelState.IsValid)
            {
                db.Entry(cANDIDATOS).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Ver", "BEMPLEOS1");
            }
            return View(cANDIDATOS);
        }

        // GET: BCANDIDATOS1/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CANDIDATOS cANDIDATOS = db.CANDIDATOS.Find(id);
            if (cANDIDATOS == null)
            {
                return HttpNotFound();
            }
            return View(cANDIDATOS);
        }

        // POST: BCANDIDATOS1/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            CANDIDATOS cANDIDATOS = db.CANDIDATOS.Find(id);
            db.CANDIDATOS.Remove(cANDIDATOS);
            db.SaveChanges();
            return RedirectToAction("Ver", "BEMPLEOS1");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Trabajoempleados/Controllers/BCONTRATISTAS1Controller.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;
using Trabajoempleados.Models;

namespace Trabajoempleados.Controllers
{
    public class BCONTRATISTAS1Controller : Controller
    {
        private bolsaempleosEntities db = new bolsaempleosEntities();


        // GET: BCONTRATISTAS1
        public ActionResult Index()
        {
            return View(db.CONTRATISTAS.ToList());
        }

        // GET: BCONTRATISTAS1/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CONTRATISTAS cONTRATISTAS = db.CONTRATISTAS.Find(id);
            if (cONTRATISTAS == null)
            {
                return HttpNotFound();
            }
            return View(cONTRATISTAS);
        }

        // GET: BCONTRATISTAS1/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: BCONTRATISTAS1/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CONTRATISTAS contra, [Bind(Include = "Id,IdContratista,Rnc,NombreEmpresa,Representante,Correo,Telefono,Contrasena,Direccion,Descripcion")] CONTRATISTAS cONTRATISTAS)
        {
            var code = string.Empty;
            var code2 = string.Empty;

            // ORIGEN DE

            code = Regex.Replace(contra.NombreEmpresa, @"[\p{P}\p{S}\p{C}\p{N}]+", "");
            code = Regex.Replace(code, @"\p{Z}+", " ");
            code = Regex.Replace(code.Trim(), @"\s+(?:[JS]R|I{1,3}|I[VX]|VI{0,3})$", "", RegexOptions.IgnoreCase);
            code = Regex.Replace(code, @"^(\p{L})[^\s]*(?:\s+(?:\p{L}+\s+(?=\p{L}))?(?:(\p{L})\p{L}*)?)?$", "$1$2").Trim();


            if (code.Length > 2)
            {
                code = code.Substring(0, 2);
            }

            code = code.ToUpperInvariant();

            int no = 0;
           
            try
            {
                no = db.CONTRATISTAS
                .OrderByDescending(x => x.Id)
                .First().Id;



                int secuencia = 1 + no;

                string codigo;
                string c1 = "00", c2 = "0";
                if (secuencia < 10)
                {
                    codigo = code + "-" + c1 + secuencia;
                }
                else if (secuencia < 100)
                {
                    codigo = code + "-" + c2 + secuencia;
                }
                else
                {
                    codigo = code + "-" + secuencia;
                }
                cONTRATISTAS.IdContratista = codigo;

            }
            catch
            {
                string c1 = "00";
                no = 0;

                int secuencia = 1 + no;

                string codigo = code + "-" + secuencia;
                cONTRATISTAS.IdContratista = codigo;

            }
            if (ModelState.IsValid)
            {
                db.CONTRATISTAS.Add(cONTRATISTAS);
                db.SaveChanges();
                return RedirectToAction("Login", "Login");
            }

            return View(cONTRATISTAS);
        }

        // GET: BCONTRATISTAS1/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CONTRATISTAS cONTRATISTAS = db.CONTRATISTAS.Find(id);
            if (cONTRATISTAS == null)
            {
                return HttpNotFound();
            }
            return View(cONTRATISTAS);
        }

        // POST: BCONTRATISTAS1/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,IdContratista,Rnc,NombreEmpresa,Representante,Correo,Telefono,Contrasena,Direccion,Descripcion")] CONTRATISTAS cONTRATISTAS)
        {
            if (ModelState.IsValid)
            {
                db.Entry(cONTRATISTAS).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Ver", "BEMPLEOS1");
            }
            return View(cONTRATISTAS);
        }

        // GET: BCONTRATISTAS1/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CONTRATISTAS cONTRATISTAS = db.CONTRATISTAS.Find(id);
            if (cONTRATISTAS == null)
            {
                return HttpNotFound();
            }
            return View(cONTRATISTAS);
        }

        // POST: BCONTRATISTAS1/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            CONTRATISTAS cONTRATISTAS = db.CONTRATISTAS.Find(id);
            db.CONTRATISTAS.Remove(cONTRATISTAS);
            db.SaveChanges();
            return RedirectToAction("Vercontratista", "BEMPLEOS1");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Trabajoempleados/Controllers/CATEGORIAsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Trabajoempleados.Models;

namespace Trabajoempleados.Controllers
{
    public class CATEGORIAsController : Controller
    {
        private bolsaempleosEntities db = new bolsaempleosEntities();

        // GET: CATEGORIAs
        public ActionResult Index()
        {
            return View(db.CATEGORIA.ToList());
        }

        // GET: CATEGORIAs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CATEGORIA cATEGORIA = db.CATEGORIA.Find(id);
            if (cATEGORIA == null)
            {
                return HttpNotFound();
            }
            return View(cATEGORIA);
        }

        // GET: CATEGORIAs/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: CATEGORIAs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Nombre")] CATEGORIA cATEGORIA)
        {
            if (ModelState.IsValid)
            {
                db.CATEGORIA.Add(cATEGORIA);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(cATEGORIA);
        }

        // GET: CATEGORIAs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CATEGORIA cATEGORIA = db.CATEGORIA.Find(id);
            if (cATEGORIA == null)
            {
                return HttpNotFound();
            }
            return View(cATEGORIA);
        }

        // POST: CATEGORIAs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Nombre")] CATEGORIA cATEGORIA)
        {
            if (ModelState.IsValid)
            {
                db.Entry(cATEGORIA).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(cATEGORIA);
        }

        // GET: CATEGORIAs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CATEGORIA cATEGORIA = db.CATEGORIA.Find(id);
            if (cATEGORIA == null)
            {
                return HttpNotFound();
            }
            return View(cATEGORIA);
        }

        // POST: CATEGORIAs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            CATEGORIA cATEGORIA = db.CATEGORIA.Find(id);
            db.CATEGORIA.Remove(cATEGORIA);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Trabajoempleados/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Trabajoempleados.Models;

namespace Trabajoempleados.Controllers
{
    public class LoginController : Controller
    {
        private bolsaempleosEntities db = new bolsaempleosEntities();
        // GET: Login
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(string Correo, string Contrasena)
        {
            combinados obj = new combinados();
 
            var admin = db.ADMINISTRADORES.FirstOrDefault(x => x.Correo == Correo && x.Contrasena == Contrasena);
            
            if (admin != null)
            {
                obj.idcontracheck = admin.IdAdmin;
                return RedirectToAction("Veradmin", "BEMPLEOS1", new { obj.idcontracheck });
            }

            else
            {
                var candidato = db.CANDIDATOS.FirstOrDefault(x => x.Correo == Correo && x.Contrasena == Contrasena);

                if (candidato != null)
                {
                    obj.idcontracheck = candidato.IdCandidato;
                    return RedirectToAction("Ver", "BEMPLEOS1", new { obj.idcontracheck });
                }
                else
                {
                    var contratista = db.CONTRATISTAS.FirstOrDefault(x => x.Correo == Correo && x.Contrasena == Contrasena);

                    if (contratista != null)
                    {

                        obj.idcontracheck = contratista.Id;
                        return RedirectToAction("Vercontratista", "BEMPLEOS1", new { obj.idcontracheck });
                    }
                    else
                    {
                        ViewBag.Mensaje = "ISDNFIS";
                        return View();
                    }
                }
            }

        }




    }
}

Trabajoempleados/Views/Shared/_Layout-2.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.min.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <link href="~/Content/themes/base/jquery-ui.min.css" rel="stylesheet" />

    <script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>
    <script src="~/Scripts/jquery-ui.js"></script>
    <link href="~/Content/footerx.css" rel="stylesheet" />
    <link href="~/Content/fondo.css" rel="stylesheet" />
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark static-top" style="margin-top:-55px;">
        <div class="container">
            <a class="navbar-brand" href="#">
                <img src="http://placehold.it/150x50?text=Logo" alt="">
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="#">
                            Bolsa Empleos
                        </a>

                    </li>

                    <li class="nav-item">
                        <a class="nav-link" href="javascript: history.go(-1)">Volver.</a>
                    </li>

                    <li class="nav-item" style="margin-top:-15px; margin-right:800px;">
                        <a class="nav-link">@Html.ActionLink("Cerrar Sesión.", "Login", "Login", new { area = "" }, new { @class = "nav-link" })</a>
                    </li>

                </ul>
            </div>
        </div>
    </nav>

    <div class="container body-content">
        @RenderBody()

    </div>

    @Scripts.Render("~/bundles/jquery")

    @Scripts.Render("~/Scripts/jquery-ui.js")
    @RenderSection("scripts", required: false)
</body>
</html>

Trabajoempleados/Views/Shared/_Layout3.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="//cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css" rel="stylesheet" />
    <link href="~/Content/Styles.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.css">
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <link href="~/Content/themes/base/jquery-ui.min.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>
    <link href="~/Content/fondo.css" rel="stylesheet" />

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    @RenderSection("styles", required: false)
</head>
<body>



    <nav class="navbar navbar-expand-lg navbar-dark bg-dark static-top" style="margin-top:-50px;">
        <div class="container">
            <a class="navbar-brand" href="#">
                <img src="http://placehold.it/150x50?text=Logo" alt="">
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="#">
                Bolsa Empleos

                        </a>
                    </li>

             

                </ul>
            </div>
        </div>
    </nav>
    @*<div class="navbar navbar-default navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <p style="margin-top:15px; color:dimgrey"> Bolsa empleos</p>
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav navbar-right">

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Registrarse ▼
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li>  @Html.ActionLink("Candidato", "Create", "BCANDIDATOS1", new { area = "" }, new { @class = "dropdown-item" })</li>
                                <li>  @Html.ActionLink("Contratista", "Create", "BCONTRATISTAS1", new { area = "" }, new { @class = "dropdown-item" })</li>
                            </ul>
                        </li>

                    </ul>
                </div>
            </div>
        </div>*@


    <div class="container body-content">
        @RenderBody()


    </div>

    @Scripts.Render("~/bundles/jquery")

    @Scripts.Render("~/Scripts/jquery-ui-1.12.1.min.js")
    <script src="https://cdn.jsdelivr.net/npm/gasparesganga-jquery-loading-overlay@2.1.6/dist/loadingoverlay.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>

Trabajoempleados/Views/Shared/_Layout4-2.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="//cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css" rel="stylesheet" />
    <link href="~/Content/Styles.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.css">
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <link href="~/Content/themes/base/jquery-ui.min.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>
    <link href="~/Content/fondo.css" rel="stylesheet" />
    <link href="~/Content/footerx.css" rel="stylesheet" />
    @RenderSection("styles", required: false)
</head>
<body>

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark static-top" style="margin-top:-50px;">
        <div class="container">
            <a class="navbar-brand" href="#">
                <img src="http://placehold.it/150x50?text=Logo" alt="">
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="#">
                            Bolsa Empleos
                        </a>

                    </li>

                    <li class="nav-item">
                        <a class="nav-link" href="javascript: history.go(-1)">Volver.</a>
                    </li>

                    <li class="nav-item" style="margin-top:-15px;">
                        <a class="nav-link">@Html.ActionLink("Cerrar Sesión.", "Login", "Login", new { area = "" }, new { @class = "nav-link" })</a>
                    </li>

                </ul>
            </div>
        </div>
    </nav>


    @*<div class="navbar navbar-default navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <p style="margin-top:15px; color:dimgrey"> Bolsa empleos</p>
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav navbar-right">
                        <li>@Html.ActionLink("Empleos", "Veradmin", "BEMPLEOS1", new { area = "" }, null)</li>
                        <li>@Html.ActionLink("Refinar Búsqueda", "verconfiltroadmin", "BEMPLEOS1", new { area = "" }, null)</li>
                        <li>@Html.ActionLink("Modificar Categorias", "Index", "CATEGORIAs", new { area = "" }, null)</li>
                        <li style="background-color: deepskyblue">@Html.ActionLink("Cerrar Sesión", "Login", "Login", new { area = "" }, null)</li>
                    </ul>
                </div>
            </div>
        </div>*@
    <div class="container body-content">
        @RenderBody()

</body>

</html>

Trabajoempleados/Views/Shared/_Layoutneutro.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="//cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css" rel="stylesheet" />
    <link href="~/Content/Styles.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.css">
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <link href="~/Content/themes/base/jquery-ui.min.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>
    <link href="~/Content/fondo.css" rel="stylesheet" />




    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    @RenderSection("styles", required: false)
</head>
<body>
 
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer class="fotter-butom">
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")

    @Scripts.Render("~/Scripts/jquery-ui-1.12.1.min.js")
    <script src="https://cdn.jsdelivr.net/npm/gasparesganga-jquery-loading-overlay@2.1.6/dist/loadingoverlay.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>